### ISSUE TITLE
Just click this thing

### ISSUE THREAD

**Issue by Arandomuseroninternet** [xstabux/Omaloon#36]
Why can't i download this mod?,it keep crashing when i try this mod

**Comment by xstabux** [comment]
Hi @Arandomuseroninternet! Which version of Omaloon are you trying to run and on which version of Mindustry? Having checked the latest available release of Omaloon on my device, I did not encounter any crashes.
Could you please clarify what exactly you did or provide a crash report?

**Comment by Arandomuseroninternet** [comment]
Omaloon v0.6f pre alpha and mindustry v7 146

**Comment by xstabux** [comment]
Could you please clarify what exactly you did and provide me a crash report?

**Comment by xstabux** [comment]
btw there will be no support for v0.6f, because the repository currently has a completely different look and content.

**Comment by xstabux** [comment]
Well, if you do not plan to provide a crash report, then support for this problem will not be provided
