### ISSUE TITLE
Tube junction crashing game

### ISSUE THREAD

**Issue by HungryCloud4913** [xstabux/Omaloon#51]
![image](https://github.com/user-attachments/assets/ac81d994-c03e-4df7-9b4b-077b242aa79e)
I placed a tube junction and my game crashed. I don't know why I'm not a block coder personally.

**Comment by uujuju1** [comment]
send the crash log

**Comment by HungryCloud4913** [comment]
I didn't even see that reply. I hope its not too late to send the crash log
![image](https://github.com/user-attachments/assets/958c4c1d-c531-4a4e-a587-b6537f904d1f)
