### ISSUE TITLE
Small shelter

### ISSUE THREAD

**Issue by BetaGames-Team** [xstabux/Omaloon#52]
### Platforms

Android

### Mindustry Build

146

### Omaloon Build

IDK (it is in Myndustry mod list)

### Issue

I can't make enought pressure to activate small shelter in survival, but in sandbox IT works perfectly.
![Screenshot_2024-12-02-23-06-13-047_io anuke mindustry](https://github.com/user-attachments/assets/0d17afc6-291c-4c69-8a9c-1ec5f812337d)

### Steps to reproduce

Its written in Issue.

### Submission

- [X] I have updated to the latest [release](https://github.com/xtabux/Omaloon/releases) or [action](https://github.com/xtabux/Omaloon/actions) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by uujuju1** [comment]
this is a feature that stabu asked and i have no clue why, that's so confusing for anyone who haven't played the mod before lmao
the pump is hardcoded to maintain a difference of 5 pressure units between the front and the back(unless the pump is pumping air out), to go around that, add more pumps in series, with a pipe in between
e.g pump -> pipe -> pump -> pipe -> pump -> shelter. each pump will add 5 pressure units, when it gets to 15, and is powered, the shelter will work
